# These are created with
# docker volume create --driver local \
#    --opt type=none \
#    --opt device=/path/to/data \
#    --opt o=bind volume_name
volumes:
  zeek_logs:
    external: true

services:

  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./configs:/benchmark/configs:ro
      - ./scripts:/benchmark/scripts:ro
      - zeek_logs:/benchmark/zeek_logs
    environment:
      - ZEEK_BRANCH=master
      - ZEEK_RUN_LENGTH=86400
    working_dir: /benchmark
    command: /benchmark/scripts/build.sh
    ports:
      - 127.0.0.1:9991-10001:9991-10001/tcp
